/*
 * Copyright (C) 2008-12  Bernhard Hobiger
 *
 * This file is part of HoDoKu.
 *
 * HoDoKu is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HoDoKu is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HoDoKu. If not, see <http://www.gnu.org/licenses/>.
 */

package sudoku;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.Stroke;
import java.text.MessageFormat;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author hobiwan
 */
public class ConfigSolverPanel extends javax.swing.JPanel implements ListDragAndDropChange {
	private static final long serialVersionUID = 1L;
	private StepConfig[] steps;
	private DefaultListModel<StepConfig> model;
	private int dropIndex = -1;
	@SuppressWarnings("unused")
	private StepConfig dropObject;
	private Color dndColor;
	private Stroke dndStroke;

	// wird true gesetzt, nachdem ein Eintrag selektiert wurde; beim
	// nächsten Klick wird dann getoggelt
	private boolean firstSelected = false;

	private boolean listView = false; // absichtlich verkehrt, damit stepList gesetzt wird

	/** Creates new form ConfigSolverPanel */
	@SuppressWarnings({ "unchecked" })
	public ConfigSolverPanel() {
		initComponents();

		Color tmpColor = UIManager.getColor("List.foreground");
		dndColor = new Color(tmpColor.getRed(), tmpColor.getGreen(), tmpColor.getBlue(), 100);
		dndStroke = new BasicStroke(2, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND);

		stepList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		stepList.setCellRenderer(new CheckBoxRenderer());
		model = new DefaultListModel<StepConfig>();
		stepList.setModel(model);
		new ListDragAndDrop(stepList, this, this);

		stepTree.setCellRenderer(new CheckRenderer());
		stepTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
		stepTree.putClientProperty("JTree.lineStyle", "Angled");

		for (int i = 1; i < Options.getInstance().getDifficultyLevels().length; i++) {
			levelComboBox.addItem(Options.getInstance().getDifficultyLevels()[i].getName());
		}

		NumbersOnlyDocument doc = new NumbersOnlyDocument();
		doc.addDocumentListener(new MyDocumentListener());
		scoreTextField.setDocument(doc);

		// modern fork (milestone 1.5): technique aside v2 + search field
		initAside();
		initSearchField();

		// Alle Werte aus den Default-Optionen setzen
		initAll(false);

		checkButtons(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		stepTree = new javax.swing.JTree();
		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		levelLabel = new javax.swing.JLabel();
		scoreLabel = new javax.swing.JLabel();
		levelComboBox = new javax.swing.JComboBox<String>();
		scoreTextField = new javax.swing.JTextField();
		upButton = new javax.swing.JButton();
		downButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		stepScrollPane = new javax.swing.JScrollPane();
		stepList = new javax.swing.JList<StepConfig>();
		jToolBar1 = new javax.swing.JToolBar();
		listButton = new javax.swing.JToggleButton();
		treeButton = new javax.swing.JToggleButton();

		stepTree.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				stepTreeMousePressed(evt);
			}
		});
		stepTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
			public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
				stepTreeValueChanged(evt);
			}
		});

		java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel"); // NOI18N
		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder(bundle.getString("ConfigSolverPanel.jPanel3.border.title"))); // NOI18N

		levelLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel")
				.getString("ConfigSolverPanel.levelLabel.mnemonic").charAt(0));
		levelLabel.setLabelFor(levelComboBox);
		levelLabel.setText(bundle.getString("ConfigSolverPanel.levelLabel.text")); // NOI18N

		scoreLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel")
				.getString("ConfigSolverPanel.scoreLabel.mnemonic").charAt(0));
		scoreLabel.setLabelFor(scoreTextField);
		scoreLabel.setText(bundle.getString("ConfigSolverPanel.scoreLabel.text")); // NOI18N

		levelComboBox.setEnabled(false);
		levelComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				levelComboBoxActionPerformed(evt);
			}
		});

		scoreTextField.setEnabled(false);

		// modern fork (milestone 1.5): jPanel3 is the technique aside now; its
		// content (level/score plus description, aliases, display name and the
		// owned options) is built in initAside()
		jPanel3.setLayout(new java.awt.BorderLayout());

		upButton.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel")
				.getString("ConfigSolverPanel.upButton.mnemonic").charAt(0));
		upButton.setText(bundle.getString("ConfigSolverPanel.upButton.text")); // NOI18N
		upButton.setEnabled(false);
		upButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				upButtonActionPerformed(evt);
			}
		});

		downButton.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel")
				.getString("ConfigSolverPanel.downButton.mnemonic").charAt(0));
		downButton.setText(bundle.getString("ConfigSolverPanel.downButton.text")); // NOI18N
		downButton.setEnabled(false);
		downButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				downButtonActionPerformed(evt);
			}
		});

		resetButton.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel")
				.getString("ConfigSolverPanel.resetButton.mnemonic").charAt(0));
		resetButton.setText(bundle.getString("ConfigSolverPanel.resetButton.text")); // NOI18N
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(downButton)
										.addGap(105, 105, 105).addComponent(resetButton))
								.addComponent(upButton).addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { downButton, upButton });

		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						// modern fork (milestone 1.5): the aside takes the available height
						.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(upButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(downButton).addComponent(resetButton))));

		jPanel4.setLayout(new java.awt.BorderLayout());

		stepList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				stepListMouseClicked(evt);
			}
		});
		stepList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				stepListValueChanged(evt);
			}
		});
		stepScrollPane.setViewportView(stepList);

		jPanel4.add(stepScrollPane, java.awt.BorderLayout.CENTER);

		listButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listview16b.png"))); // NOI18N
		listButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				listButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(listButton);

		treeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/treeview16b.png"))); // NOI18N
		treeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				treeButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(treeButton);

		jPanel4.add(jToolBar1, java.awt.BorderLayout.NORTH);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void stepTreeMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_stepTreeMousePressed
		TreePath path = stepTree.getPathForLocation(evt.getX(), evt.getY());
		if (path == null) {
			return;
		}
		CheckNode act = (CheckNode) path.getLastPathComponent();
		CheckNode last = (CheckNode) stepTree.getLastSelectedPathComponent();
		if (act != null && last != null && act == last) {
			last.toggleSelectionState();
			stepTree.repaint();
		}
	}// GEN-LAST:event_stepTreeMousePressed

	private void stepTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {// GEN-FIRST:event_stepTreeValueChanged
//        CheckNode last = (CheckNode)stepTree.getLastSelectedPathComponent();
//        last.toggleSelectionState();
//        stepTree.repaint();
	}// GEN-LAST:event_stepTreeValueChanged

	private void treeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_treeButtonActionPerformed
		checkButtons(false);
	}// GEN-LAST:event_treeButtonActionPerformed

	private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_listButtonActionPerformed
		checkButtons(true);
	}// GEN-LAST:event_listButtonActionPerformed

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetButtonActionPerformed
		initAll(true);
	}// GEN-LAST:event_resetButtonActionPerformed

	private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_downButtonActionPerformed
		int index = stepList.getSelectedIndex();
		if (index < steps.length - 1) {
			moveOneStep(index, true);
//            StepConfig dummy = steps[index];
//            steps[index] = steps[index + 1];
//            steps[index + 1] = dummy;
//            int dummyIndex = steps[index].getIndex();
//            steps[index].setIndex(steps[index + 1].getIndex());
//            steps[index + 1].setIndex(dummyIndex);
//            model.remove(index);
//            model.add(index + 1, steps[index + 1]);
//            stepList.setSelectedIndex(index + 1);
//            stepList.ensureIndexIsVisible(index + 1);
//            stepList.repaint();
		}
	}// GEN-LAST:event_downButtonActionPerformed

	private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_upButtonActionPerformed
		int index = stepList.getSelectedIndex();
		if (index > 0) {
			moveOneStep(index, false);
//            StepConfig dummy = steps[index];
//            steps[index] = steps[index - 1];
//            steps[index - 1] = dummy;
//            int dummyIndex = steps[index].getIndex();
//            steps[index].setIndex(steps[index - 1].getIndex());
//            steps[index - 1].setIndex(dummyIndex);
//            model.remove(index);
//            model.add(index - 1, steps[index - 1]);
//            stepList.setSelectedIndex(index - 1);
//            stepList.ensureIndexIsVisible(index - 1);
//            stepList.repaint();
		}
	}// GEN-LAST:event_upButtonActionPerformed

	private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_levelComboBoxActionPerformed
		int index = stepList.getSelectedIndex();
		if (index != -1) {
			StepConfig conf = stepList.getSelectedValue();
			conf.setLevel(levelComboBox.getSelectedIndex() + 1);
		}
	}// GEN-LAST:event_levelComboBoxActionPerformed

	private void stepListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_stepListValueChanged
		if (evt == null || !evt.getValueIsAdjusting()) {
			if (stepList.getSelectedValue() == null) {
				return;
			}
			firstSelected = true;
			levelComboBox.setEnabled(true);
			scoreTextField.setEnabled(true);
			StepConfig conf = stepList.getSelectedValue();
			levelComboBox.setSelectedIndex(conf.getLevel() - 1);
			scoreTextField.setText(Integer.toString(conf.getBaseScore()));
			// modern fork (milestone 1.5): refresh the technique aside
			updateAside(conf);
			// "Nach oben" und "Nach unten" Buttons anpassen (modern fork:
			// reordering is disabled while the search filter is active, the
			// filtered indices do not match the solve order)
			boolean canReorder = !isFiltered();
			upButton.setEnabled(canReorder && stepList.getSelectedIndex() > 0);
			downButton.setEnabled(canReorder && stepList.getSelectedIndex() < steps.length - 1);
		}
	}// GEN-LAST:event_stepListValueChanged

	private void stepListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_stepListMouseClicked
		if (firstSelected) {
			firstSelected = false;
		} else {
			int index = stepList.locationToIndex(evt.getPoint());
			if (index == stepList.getSelectedIndex()) {
				StepConfig conf = stepList.getSelectedValue();
				conf.setEnabled(!conf.isEnabled());
				stepList.repaint();
			}
		}
	}// GEN-LAST:event_stepListMouseClicked

	private void moveOneStep(int index, boolean up) {
		// System.out.println("move one step: " + index + "/" + up);
		int toIndex = up ? index + 1 : index - 1;
		StepConfig dummy = steps[index];
		steps[index] = steps[toIndex];
		steps[toIndex] = dummy;
		int dummyIndex = steps[index].getIndex();
		steps[index].setIndex(steps[toIndex].getIndex());
		steps[toIndex].setIndex(dummyIndex);
		model.remove(index);
		model.add(toIndex, steps[toIndex]);
		stepList.setSelectedIndex(toIndex);
		stepList.ensureIndexIsVisible(toIndex);
		stepList.repaint();
	}

	@Override
	public void moveStep(int fromIndex, int toIndex) {
		if (isFiltered()) {
			// modern fork (milestone 1.5): while the search filter is active the
			// model indices do not match the solve order — no reordering
			return;
		}
		// System.out.println("moving: " + fromIndex + "/" + toIndex);
		boolean up = fromIndex < toIndex ? true : false;
		int anz = Math.abs(fromIndex - toIndex);
		if (up) {
			anz--;
		}
		for (int i = 0; i < anz; i++) {
			moveOneStep(fromIndex, up);
			if (up) {
				fromIndex++;
			} else {
				fromIndex--;
			}
		}
	}

	@Override
	public void setDropLocation(int index, StepConfig object) {
		if (isFiltered()) {
			dropIndex = -1;
			return;
		}
		dropIndex = index;
		dropObject = object;
		if (index != -1) {
			if (index <= stepList.getFirstVisibleIndex() + 1) {
				stepList.ensureIndexIsVisible(index - 1);
			} else if (index >= stepList.getLastVisibleIndex() - 1) {
				stepList.ensureIndexIsVisible(index + 1);
			}
		}
	}

	public void okPressed() {
		// Alle Werte übernehmen
		Options.getInstance().solverSteps = Options.getInstance().copyStepConfigs(steps, false, true);
		Options.getInstance().adjustOrgSolverSteps();
		// modern fork (milestone 1.5): apply the buffered display-name choices
		// (setPreferredDisplayName removes the preference when the default name
		// was chosen)
		solver.modern.registry.TechniqueRegistry registry = solver.modern.registry.TechniqueRegistry.getInstance();
		for (java.util.Map.Entry<SolutionType, String> entry : pendingDisplayNames.entrySet()) {
			registry.setPreferredDisplayName(entry.getKey(), entry.getValue());
		}
		pendingDisplayNames.clear();
	}

	/**
	 * Modern fork (milestone 1.8, A5): rebuilds the tab from the current options
	 * state when the user enters it.
	 */
	public void tabEntered() {
		initAll(false);
	}

	private void initAll(boolean setDefault) {
		// Zuerst die Daten zurücksetzen
		if (setDefault) {
			steps = Options.getInstance().copyStepConfigs(Options.DEFAULT_SOLVER_STEPS, true, false);
		} else {
			steps = Options.getInstance().copyStepConfigs(Options.getInstance().solverSteps, true, false);
		}

		// Liste neu laden (modern fork: through the search filter)
		applyFilter();
		stepList.setSelectedIndex(-1);
		stepList.ensureIndexIsVisible(0);
		stepList.repaint();
		levelComboBox.setSelectedIndex(-1);
		scoreTextField.setText("");
		clearAside();

		// Baum neu laden
		buildTree();
	}

	public void buildTree() {
		// modern fork (milestone 1.5): the tree honors the search filter too
		solver.modern.registry.TechniqueRegistry registry = solver.modern.registry.TechniqueRegistry.getInstance();
		String query = searchField != null ? searchField.getText() : null;
		CheckNode root = new CheckNode();
		for (int i = 0; i < steps.length; i++) {
			if (!registry.matches(steps[i].getType(), query)) {
				continue;
			}
			// modern fork (milestone 1.9): group by the registry family (folder
			// model), not the legacy SolutionCategory
			solver.modern.registry.Family folder = solver.modern.registry.TechniqueFolders
					.folderOf(steps[i].getType());
			@SuppressWarnings("unchecked")
			Enumeration<CheckNode> en = (Enumeration<CheckNode>) (Enumeration<?>) root.children();
			CheckNode act = null;
			while (en.hasMoreElements()) {
				act = en.nextElement();
				if (act.getFamily() == folder) {
					break;
				}
				act = null;
			}
			if (act == null) {
				// new folder
				act = new CheckNode(solver.modern.registry.TechniqueFolders.folderName(folder), true,
						steps[i].isEnabled() ? CheckNode.FULL : CheckNode.NONE, null, false, false, false, null);
				act.setFamily(folder);
				root.add(act);
			}
			// modern fork (milestone 1.5): render the preferred display name
			act.add(new CheckNode(steps[i].toString(), false,
					steps[i].isEnabled() ? CheckNode.FULL : CheckNode.NONE, steps[i], false, false, false, null));
			if (act.getSelectionState() == CheckNode.FULL && !steps[i].isEnabled()) {
				act.setSelectionState(CheckNode.HALF);
			}
			if (act.getSelectionState() == CheckNode.NONE && steps[i].isEnabled()) {
				act.setSelectionState(CheckNode.HALF);
			}
		}
		DefaultTreeModel tmpModel = new DefaultTreeModel(root);
		stepTree.setModel(tmpModel);
		stepTree.setShowsRootHandles(true);
		stepTree.setRootVisible(false);
		stepTree.setRowHeight(-1);
	}

	private void checkButtons(boolean setList) {
		boolean changeView = false;
		if (listView != setList) {
			changeView = true;
		}
		listView = setList;
		if (listView) {
			listButton.setSelected(true);
			treeButton.setSelected(false);
			if (changeView) {
				stepScrollPane.setViewportView(stepList);
				if (stepList.getSelectedIndex() >= 0) {
					stepListValueChanged(null);
				}
			}
			stepList.requestFocusInWindow();
		} else {
			listButton.setSelected(false);
			treeButton.setSelected(true);
			if (changeView) {
				buildTree();
				stepScrollPane.setViewportView(stepTree);
				levelComboBox.setEnabled(false);
				scoreTextField.setEnabled(false);
			}
			stepTree.requestFocusInWindow();
		}
	}

	@SuppressWarnings("rawtypes")
	class CheckBoxRenderer extends JCheckBox implements ListCellRenderer {
		private static final long serialVersionUID = 1L;
		private boolean isTargetCell;
		@SuppressWarnings("unused")
		private int index;

		CheckBoxRenderer() {
		}

		@Override
		public Component getListCellRendererComponent(JList listBox, Object obj, int index, boolean isSelected,
				boolean hasFocus) {
//            System.out.println(((StepConfig)obj).toString());
			if (isSelected) {
				Color bg = UIManager.getColor("List.selectionBackground");
				if (bg == null) {
					bg = UIManager.getColor("List[Selected].textBackground");
				}
				Color fg = UIManager.getColor("List.selectionForeground");
				if (fg == null) {
					fg = UIManager.getColor("List[Selected].textForeground");
				}
				setBackground(bg);
				setForeground(fg);
//                System.out.println("SBG: " + bg);
//                System.out.println("SFG: " + fg);
				// necessary for Nimbus!
				setOpaque(true);
			} else {
				setBackground(UIManager.getColor("List.background"));
				setForeground(UIManager.getColor("List.foreground"));
//                System.out.println("BG: " + UIManager.getColor("List.background"));
//                System.out.println("FG: " + UIManager.getColor("List.foreground"));
				// necessary for Nimbus!
				setOpaque(false);
			}
			setText(((StepConfig) obj).toString());
			setSelected(((StepConfig) obj).isEnabled());

			isTargetCell = false;
			this.index = index;
			if (index == dropIndex) {
				isTargetCell = true;
			}
			return this;
		}

		@Override
		public void paintComponent(Graphics g) {
			super.paintComponent(g);
//            System.out.println("paintComponent: " + getText()+ "/"+ getForeground() + "/" + getBackground());
			Graphics2D g2 = (Graphics2D) g;
			if (isTargetCell) {
				Insets insets = getInsets();
				g2.setColor(dndColor);
				g2.setStroke(dndStroke);
				// g2.drawLine(insets.left, 1, insets.right, 1);
				g2.drawLine(insets.left - 2, 0, insets.left - 2, 3);
				g2.drawLine(insets.left - 1, 2, getSize().width, 2);
			}
		}

	}

	// ------------------------------------------------------------------
	// modern fork (milestone 1.5): technique aside v2.
	//
	// The aside is a MIRROR: every option keeps its canonical classic tab
	// (ConfigStepPanel), the aside editors share the Swing models of the
	// classic controls (ButtonModel / ComboBoxModel / Document), so both
	// views stay in sync and the value is written to Options exactly once,
	// in ConfigStepPanel.okPressed(). Display-name choices are buffered in
	// pendingDisplayNames and applied in okPressed() (dialog semantics).
	// ------------------------------------------------------------------

	/** the classic Steps tab, wired by ConfigDialog (null when standalone) */
	private ConfigStepPanel classicStepPanel;
	private javax.swing.JPanel asideContent;
	private javax.swing.JTextArea descriptionArea;
	private javax.swing.JLabel aliasesCaption;
	private javax.swing.JTextArea aliasesArea;
	private javax.swing.JLabel displayNameCaption;
	private javax.swing.JComboBox<String> displayNameComboBox;
	private javax.swing.JLabel optionsCaption;
	private javax.swing.JPanel optionsPanel;
	/** display-name choices buffered until okPressed() */
	private final java.util.Map<SolutionType, String> pendingDisplayNames = new java.util.HashMap<SolutionType, String>();
	/** one mirror per option key, created lazily, models shared with the classic tab */
	private final java.util.Map<String, javax.swing.JComponent> optionMirrors = new java.util.HashMap<String, javax.swing.JComponent>();
	/** guards against combo events fired while the aside is being populated */
	private boolean updatingAside = false;

	/** Wired by ConfigDialog so the aside can mirror the classic Steps tab. */
	public void setClassicStepPanel(ConfigStepPanel panel) {
		classicStepPanel = panel;
	}

	/** search field over the technique list (modern fork, milestone 1.5) */
	private javax.swing.JTextField searchField;

	/** true while the search filter hides part of the technique list */
	private boolean isFiltered() {
		return searchField != null && !searchField.getText().trim().isEmpty();
	}

	/** Builds the search field and adds it to the list/tree toolbar. */
	private void initSearchField() {
		java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel");
		searchField = new javax.swing.JTextField();
		searchField.setToolTipText(bundle.getString("ConfigSolverPanel.searchField.tooltip"));
		searchField.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE,
				searchField.getPreferredSize().height));
		searchField.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void insertUpdate(DocumentEvent e) {
				applyFilter();
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				applyFilter();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				applyFilter();
			}
		});
		jToolBar1.addSeparator();
		jToolBar1.add(searchField);
	}

	/**
	 * Reloads the list model with the steps matching the search filter
	 * (name + aliases + description via the registry) and keeps the tree in
	 * sync. Selection survives if the selected technique still matches.
	 */
	private void applyFilter() {
		if (model == null || steps == null) {
			return;
		}
		StepConfig selected = stepList.getSelectedValue();
		String query = searchField != null ? searchField.getText() : null;
		solver.modern.registry.TechniqueRegistry registry = solver.modern.registry.TechniqueRegistry.getInstance();
		model.removeAllElements();
		for (int i = 0; i < steps.length; i++) {
			if (registry.matches(steps[i].getType(), query)) {
				model.addElement(steps[i]);
			}
		}
		if (selected != null && model.contains(selected)) {
			stepList.setSelectedValue(selected, true);
		}
		stepList.repaint();
		buildTree();
	}

	/** Builds the aside content inside jPanel3 (called once from the constructor). */
	private void initAside() {
		java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel");

		descriptionArea = makeWrappedArea();
		aliasesCaption = new javax.swing.JLabel(bundle.getString("ConfigSolverPanel.aliasesCaption.text"));
		aliasesArea = makeWrappedArea();
		displayNameCaption = new javax.swing.JLabel(bundle.getString("ConfigSolverPanel.displayNameCaption.text"));
		displayNameComboBox = new javax.swing.JComboBox<String>();
		displayNameComboBox.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				displayNameChosen();
			}
		});
		optionsCaption = new javax.swing.JLabel(bundle.getString("ConfigSolverPanel.optionsCaption.text"));
		optionsPanel = new javax.swing.JPanel();
		optionsPanel.setLayout(new javax.swing.BoxLayout(optionsPanel, javax.swing.BoxLayout.Y_AXIS));
		optionsPanel.setOpaque(false);

		asideContent = new ScrollablePanel();
		asideContent.setLayout(new java.awt.GridBagLayout());
		asideContent.setOpaque(false);
		java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
		gbc.insets = new java.awt.Insets(2, 4, 2, 4);
		gbc.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

		gbc.gridy = 0;
		gbc.gridx = 0;
		gbc.weightx = 0;
		asideContent.add(levelLabel, gbc);
		gbc.gridx = 1;
		gbc.weightx = 1;
		asideContent.add(levelComboBox, gbc);
		gbc.gridy++;
		gbc.gridx = 0;
		gbc.weightx = 0;
		asideContent.add(scoreLabel, gbc);
		gbc.gridx = 1;
		gbc.weightx = 1;
		asideContent.add(scoreTextField, gbc);

		gbc.gridy++;
		gbc.gridx = 0;
		gbc.gridwidth = 2;
		gbc.weightx = 1;
		asideContent.add(descriptionArea, gbc);
		gbc.gridy++;
		asideContent.add(aliasesCaption, gbc);
		gbc.gridy++;
		asideContent.add(aliasesArea, gbc);
		gbc.gridy++;
		gbc.gridwidth = 1;
		gbc.weightx = 0;
		asideContent.add(displayNameCaption, gbc);
		gbc.gridx = 1;
		gbc.weightx = 1;
		asideContent.add(displayNameComboBox, gbc);
		gbc.gridy++;
		gbc.gridx = 0;
		gbc.gridwidth = 2;
		asideContent.add(optionsCaption, gbc);
		gbc.gridy++;
		asideContent.add(optionsPanel, gbc);
		// filler that soaks up the remaining height
		gbc.gridy++;
		gbc.weighty = 1;
		gbc.fill = java.awt.GridBagConstraints.BOTH;
		javax.swing.JPanel filler = new javax.swing.JPanel();
		filler.setOpaque(false);
		asideContent.add(filler, gbc);

		javax.swing.JScrollPane asideScrollPane = new javax.swing.JScrollPane(asideContent,
				javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
				javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		asideScrollPane.setBorder(null);
		asideScrollPane.getViewport().setOpaque(false);
		asideScrollPane.setOpaque(false);
		jPanel3.add(asideScrollPane, java.awt.BorderLayout.CENTER);
	}

	/** Shows technique data of the selected step in the aside. */
	private void updateAside(StepConfig conf) {
		if (descriptionArea == null) {
			return;
		}
		updatingAside = true;
		try {
			SolutionType type = conf.getType();
			solver.modern.registry.TechniqueRegistry registry = solver.modern.registry.TechniqueRegistry.getInstance();
			solver.modern.registry.TechniqueInfo info = registry.get(type);
			setAsideDetailVisible(info != null);
			if (info != null) {
				java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel");
				descriptionArea.setText(info.getDescription());
				aliasesArea.setText(info.getAliases().isEmpty() ? bundle.getString("ConfigSolverPanel.noAliases.text")
						: String.join(", ", info.getAliases()));
				displayNameComboBox.removeAllItems();
				displayNameComboBox.addItem(info.getDisplayNameDefault());
				for (String alias : info.getAliases()) {
					displayNameComboBox.addItem(alias);
				}
				String current = pendingDisplayNames.containsKey(type) ? pendingDisplayNames.get(type)
						: registry.getDisplayName(type);
				boolean present = false;
				for (int i = 0; i < displayNameComboBox.getItemCount(); i++) {
					if (displayNameComboBox.getItemAt(i).equals(current)) {
						present = true;
						break;
					}
				}
				if (!present) {
					// a custom persisted name that is not an alias: keep it choosable
					displayNameComboBox.addItem(current);
				}
				displayNameComboBox.setSelectedItem(current);
			}
			rebuildOptionRows(type);
		} finally {
			updatingAside = false;
		}
	}

	/** Clears the aside (no selection). */
	private void clearAside() {
		if (descriptionArea == null) {
			return;
		}
		updatingAside = true;
		try {
			descriptionArea.setText("");
			aliasesArea.setText("");
			displayNameComboBox.removeAllItems();
			optionsPanel.removeAll();
			setAsideDetailVisible(false);
			optionsPanel.revalidate();
			optionsPanel.repaint();
		} finally {
			updatingAside = false;
		}
	}

	private void setAsideDetailVisible(boolean visible) {
		descriptionArea.setVisible(visible);
		aliasesCaption.setVisible(visible);
		aliasesArea.setVisible(visible);
		displayNameCaption.setVisible(visible);
		displayNameComboBox.setVisible(visible);
		optionsCaption.setVisible(visible);
		optionsPanel.setVisible(visible);
	}

	/** The user chose a display name in the aside: buffer it until OK. */
	private void displayNameChosen() {
		if (updatingAside) {
			return;
		}
		StepConfig conf = stepList.getSelectedValue();
		String name = (String) displayNameComboBox.getSelectedItem();
		if (conf == null || name == null) {
			return;
		}
		pendingDisplayNames.put(conf.getType(), name);
	}

	/** Rebuilds the option rows of the aside for one technique. */
	private void rebuildOptionRows(SolutionType type) {
		optionsPanel.removeAll();
		int rows = 0;
		if (classicStepPanel != null) {
			solver.modern.registry.TechniqueRegistry registry = solver.modern.registry.TechniqueRegistry.getInstance();
			for (solver.modern.registry.OptionInfo option : registry.optionsOwnedBy(type)) {
				if (addOptionRow(option, type, true)) {
					rows++;
				}
			}
			// affected-but-not-owned options (grayed editor, click navigates to
			// the owner) are structurally supported; the relation has no
			// instances today — if the registry ever grows one, list it here
			for (solver.modern.registry.OptionInfo option : affectedNotOwnedOptions(type)) {
				if (addOptionRow(option, type, false)) {
					rows++;
				}
			}
		}
		optionsCaption.setVisible(rows > 0);
		optionsPanel.setVisible(rows > 0);
		optionsPanel.revalidate();
		optionsPanel.repaint();
		asideContent.revalidate();
		asideContent.repaint();
	}

	/**
	 * Options that affect the given technique without being owned by it.
	 * Empty today (see rebuildOptionRows); the grayed+navigate rendering is
	 * already implemented for when the relation gets its first instance.
	 */
	private java.util.List<solver.modern.registry.OptionInfo> affectedNotOwnedOptions(SolutionType type) {
		return java.util.Collections.emptyList();
	}

	/**
	 * Adds one option row to the aside.
	 *
	 * @param option the registry row of the option
	 * @param selected the selected technique
	 * @param owned false renders the structural affected-but-not-owned case:
	 *            editor grayed, click navigates to the first owner
	 * @return true if the row was added (the option has a classic editor)
	 */
	private boolean addOptionRow(solver.modern.registry.OptionInfo option, SolutionType selected, boolean owned) {
		javax.swing.JComponent editor = mirrorFor(option.getKey());
		if (editor == null) {
			return false;
		}
		java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel");
		String tooltip = "<html><body style='width:280px'>" + option.getDescription() + "</body></html>";
		editor.setToolTipText(tooltip);
		editor.setEnabled(owned);

		javax.swing.JPanel row = new javax.swing.JPanel(new java.awt.GridBagLayout());
		row.setOpaque(false);
		row.setAlignmentX(0f);
		java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
		gbc.insets = new java.awt.Insets(1, 0, 1, 4);
		gbc.anchor = java.awt.GridBagConstraints.WEST;
		gbc.gridx = 0;
		gbc.gridy = 0;
		String labelText = classicStepPanel.getOptionLabelText(option.getKey());
		if (labelText != null) {
			javax.swing.JLabel label = new javax.swing.JLabel(labelText);
			label.setToolTipText(tooltip);
			label.setEnabled(owned);
			row.add(label, gbc);
			gbc.gridx = 1;
			gbc.weightx = 1;
			gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
			row.add(editor, gbc);
		} else {
			gbc.gridwidth = 2;
			gbc.weightx = 1;
			gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
			row.add(editor, gbc);
		}

		// scope label when the option affects other techniques as well
		java.util.List<String> others = new java.util.ArrayList<String>();
		solver.modern.registry.TechniqueRegistry registry = solver.modern.registry.TechniqueRegistry.getInstance();
		for (SolutionType owner : option.getOwners()) {
			if (owner != selected) {
				others.add(registry.getDisplayName(owner));
			}
		}
		if (!others.isEmpty()) {
			java.util.Collections.sort(others);
			StringBuilder scope = new StringBuilder(bundle.getString("ConfigSolverPanel.alsoAffects.text"));
			int shown = Math.min(others.size(), 3);
			for (int i = 0; i < shown; i++) {
				scope.append(i == 0 ? " " : ", ").append(others.get(i));
			}
			if (others.size() > shown) {
				scope.append(", +").append(java.text.MessageFormat
						.format(bundle.getString("ConfigSolverPanel.moreOwners.text"), others.size() - shown));
			}
			javax.swing.JLabel scopeLabel = new javax.swing.JLabel(scope.toString());
			scopeLabel.setFont(scopeLabel.getFont()
					.deriveFont(java.awt.Font.ITALIC, scopeLabel.getFont().getSize2D() - 1f));
			scopeLabel.setForeground(javax.swing.UIManager.getColor("Label.disabledForeground"));
			scopeLabel.setToolTipText("<html><body style='width:280px'>" + String.join(", ", others) + "</body></html>");
			gbc.gridx = 0;
			gbc.gridy = 1;
			gbc.gridwidth = 2;
			gbc.weightx = 1;
			gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
			row.add(scopeLabel, gbc);
		}

		if (!owned && !option.getOwners().isEmpty()) {
			// structural affected-but-not-owned case: click navigates to the owner
			final SolutionType owner = option.getOwners().iterator().next();
			row.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
			row.setToolTipText(java.text.MessageFormat.format(bundle.getString("ConfigSolverPanel.goToOwner.text"),
					registry.getDisplayName(owner)));
			row.addMouseListener(new java.awt.event.MouseAdapter() {
				@Override
				public void mouseClicked(java.awt.event.MouseEvent evt) {
					navigateToTechnique(owner);
				}
			});
		}

		optionsPanel.add(row);
		return true;
	}

	/** Selects a technique in the step list (used by not-owned option rows). */
	private void navigateToTechnique(SolutionType type) {
		for (int i = 0; i < model.getSize(); i++) {
			if (model.get(i).getType() == type) {
				stepList.setSelectedIndex(i);
				stepList.ensureIndexIsVisible(i);
				return;
			}
		}
	}

	/**
	 * The aside mirror of one classic option editor: created once per option
	 * key, its Swing model shared with the classic control so both views stay
	 * in sync without extra plumbing.
	 */
	@SuppressWarnings("unchecked")
	private javax.swing.JComponent mirrorFor(String optionKey) {
		javax.swing.JComponent mirror = optionMirrors.get(optionKey);
		if (mirror != null) {
			return mirror;
		}
		javax.swing.JComponent classic = classicStepPanel.getOptionEditor(optionKey);
		if (classic instanceof javax.swing.JCheckBox) {
			javax.swing.JCheckBox classicBox = (javax.swing.JCheckBox) classic;
			javax.swing.JCheckBox box = new javax.swing.JCheckBox(classicBox.getText());
			box.setModel(classicBox.getModel());
			box.setOpaque(false);
			mirror = box;
		} else if (classic instanceof javax.swing.JComboBox) {
			javax.swing.JComboBox<String> combo = new javax.swing.JComboBox<String>();
			combo.setModel(((javax.swing.JComboBox<String>) classic).getModel());
			mirror = combo;
		} else if (classic instanceof javax.swing.JTextField) {
			javax.swing.JTextField field = new javax.swing.JTextField();
			field.setDocument(((javax.swing.JTextField) classic).getDocument());
			field.setColumns(5);
			mirror = field;
		}
		if (mirror != null) {
			optionMirrors.put(optionKey, mirror);
		}
		return mirror;
	}

	/** Read-only wrapping text area styled like a label. */
	private static javax.swing.JTextArea makeWrappedArea() {
		javax.swing.JTextArea area = new javax.swing.JTextArea();
		area.setEditable(false);
		area.setFocusable(false);
		area.setLineWrap(true);
		area.setWrapStyleWord(true);
		area.setOpaque(false);
		area.setBorder(null);
		java.awt.Font font = javax.swing.UIManager.getFont("Label.font");
		if (font != null) {
			area.setFont(font);
		}
		return area;
	}

	/** JPanel that tracks the viewport width so wrapped text areas re-wrap. */
	private static class ScrollablePanel extends javax.swing.JPanel implements javax.swing.Scrollable {
		private static final long serialVersionUID = 1L;

		@Override
		public java.awt.Dimension getPreferredScrollableViewportSize() {
			return getPreferredSize();
		}

		@Override
		public int getScrollableUnitIncrement(java.awt.Rectangle visibleRect, int orientation, int direction) {
			return 16;
		}

		@Override
		public int getScrollableBlockIncrement(java.awt.Rectangle visibleRect, int orientation, int direction) {
			return 64;
		}

		@Override
		public boolean getScrollableTracksViewportWidth() {
			return true;
		}

		@Override
		public boolean getScrollableTracksViewportHeight() {
			return false;
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton downButton;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JComboBox<String> levelComboBox;
	private javax.swing.JLabel levelLabel;
	private javax.swing.JToggleButton listButton;
	private javax.swing.JButton resetButton;
	private javax.swing.JLabel scoreLabel;
	private javax.swing.JTextField scoreTextField;
	private javax.swing.JList<StepConfig> stepList;
	private javax.swing.JScrollPane stepScrollPane;
	private javax.swing.JTree stepTree;
	private javax.swing.JToggleButton treeButton;
	private javax.swing.JButton upButton;
	// End of variables declaration//GEN-END:variables

	class MyDocumentListener implements DocumentListener {
		@Override
		public void insertUpdate(DocumentEvent e) {
			update(e);
		}

		@Override
		public void removeUpdate(DocumentEvent e) {
			update(e);
		}

		@Override
		public void changedUpdate(DocumentEvent e) {
			// we won't ever get this with a PlainDocument
		}

		private void update(DocumentEvent e) {
			String txt = scoreTextField.getText().trim();
			if (txt == null || txt.isEmpty()) {
				return;
			}
			StepConfig conf = stepList.getSelectedValue();
			try {
				int value = Integer.parseInt(txt);
				conf.setBaseScore(value);
			} catch (NumberFormatException ex) {
				MessageFormat formatter = new MessageFormat(java.util.ResourceBundle
						.getBundle("intl/ConfigSolverPanel.invalid_value").getString("MainFrame.invalid_filename"));
				String msg = formatter.format(new Object[] { txt });
				JOptionPane.showMessageDialog(null, msg, java.util.ResourceBundle.getBundle("intl/ConfigSolverPanel")
						.getString("ConfigSolverPanel.invalid_input"), JOptionPane.ERROR_MESSAGE);
			}
		}
	}
}
